"$schema" = 'https://starship.rs/config-schema.json'

format = """
╭─\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$citus\
$sudo\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
╰╴>\
$jobs\
$time\
$battery\
$status\
$os\
$container\
$netns\
$shell\
$character"""

[username]
show_always = true
style_user = "bright-yellow"
style_root = "bold red"
format = "[ $user]($style) @"

[hostname]
ssh_only = false
ssh_symbol = "󱘖  "
trim_at = "."
detect_env_vars = []
format = " [$ssh_symbol](bright-cyan)[$hostname]($style) "
style = "green bold"
disabled = false
aliases = {}

[directory]
format = "[in ](bold white)[$path]($style) "
style = "fg:123"
truncation_length = 8
truncation_symbol = '.../'
truncate_to_repo = false

[time]
disabled = false
format = '[ ](fg:8) [ $time ]($style)'
style = "fg:250"
time_format = "%H:%M:%S"

[character]
success_symbol = "[❯](bold bright-green)"
error_symbol = "[❯](bold red)"

[git_branch]
symbol = ' '
format = 'on [$symbol](bold purple)[$branch(:$remote_branch)]($style) '
style = 'bold purple'


[os]
disabled = false
format = '[$symbol]($style)'
style = "fg:183"

[os.symbols]
Kali = "  "
Raspbian = " "
AlmaLinux = "  "

[python]
symbol = ' '

[rust]
symbol = ' '
